### ISSUE TITLE
Integer Negation 

### ISSUE THREAD

**Issue by dknz2008** [DavePearce/JEVM#1]
Integer Negation is currently not working correctly. 

Example:

WRITING: 0x0000000000000000000000000000000000000000000000000000000000000001 TO 0x0000000000000000000000000000000000000000000000000000000000000000
WRITING: 0x0000000000000000000000000000000000000000000000000000000000000007 TO 0x0000000000000000000000000000000000000000000000000000000000000001
WRITING: 0x0000000000000000000000000000000000000000000000000000000000000002 TO 0x0000000000000000000000000000000000000000000000000000000000000000
LHS=0x0000000000000000000000000000000000000000000000000000000000000007
RHS=0x0000000000000000000000000000000000000000000000000000000000000001
GOT: 0x00000001FFFFFFFF00000001FFFFFFFF00000001FFFFFFFF0000000000000006
WRITING: 0x00000001FFFFFFFF00000001FFFFFFFF00000001FFFFFFFF0000000000000006 TO 0x0000000000000000000000000000000000000000000000000000000000000001

**Comment by DavePearce** [comment]
OK, have pushed a bunch of fixes through to `develop` now.

**Comment by DavePearce** [comment]
Ok, have just pushed through another release (v0.1.3) which includes all fixes for arithmetic operations so far.
